site_name: netTerrain 9.1
# site_url: http://martin.koen.gitlab.io/
theme:
  name: material
  custom_dir: 'material'
  logo: 'assets/images/logo.png'
  font:
    text: Roboto
    code: Roboto Mono
  
plugins:
    - search
    - with-pdf:
        #cover_subtitle: netTerrain 9.1
        cover_logo: material/assets/images/netTerrain_User_Guide_9.jpg
        output_path: pdf/netterrain_9.1.pdf
        # author: Graphical Networks
        # copyright: netTerrain
        custom_template_path: custom_pdf
        ordered_chapter_level: 0
        toc_level: 3
        # two_columns_level: 3
        debug_html: true
        show_anchors: true


      